{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "55bb23eb-01b5-48d4-ab9e-0ae24526ba4d",
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2025-11-30 16:22:09.331 WARNING streamlit.runtime.scriptrunner_utils.script_run_context: Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-30 16:22:09.333 WARNING streamlit.runtime.scriptrunner_utils.script_run_context: Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-30 16:22:10.348 \n",
      "  \u001b[33m\u001b[1mWarning:\u001b[0m to view this Streamlit app on a browser, run it with the following\n",
      "  command:\n",
      "\n",
      "    streamlit run C:\\Users\\HARSHITHA SRI\\anaconda3\\Lib\\site-packages\\ipykernel_launcher.py [ARGUMENTS]\n",
      "2025-11-30 16:22:10.349 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-30 16:22:10.355 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-30 16:22:10.357 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-30 16:22:16.566 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-30 16:22:16.569 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-30 16:22:16.571 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-30 16:22:16.572 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-30 16:22:16.574 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-30 16:22:16.575 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-30 16:22:16.576 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-30 16:22:16.577 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-30 16:22:16.577 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-30 16:22:16.578 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-30 16:22:16.579 Session state does not function when running a script without `streamlit run`\n",
      "2025-11-30 16:22:16.580 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-30 16:22:16.581 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-30 16:22:16.583 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-30 16:22:16.585 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-30 16:22:16.586 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-30 16:22:16.588 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-30 16:22:16.590 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-30 16:22:16.591 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-30 16:22:16.593 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-30 16:22:16.594 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-30 16:22:16.596 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-30 16:22:16.597 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-30 16:22:16.600 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-30 16:22:16.602 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-30 16:22:16.605 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-30 16:22:16.606 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-30 16:22:16.608 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-30 16:22:16.609 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-30 16:22:16.612 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-30 16:22:16.614 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-30 16:22:16.615 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-30 16:22:16.617 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-30 16:22:16.619 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-30 16:22:16.621 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-30 16:22:16.623 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-30 16:22:16.624 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-30 16:22:16.665 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-30 16:22:16.668 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-30 16:22:16.671 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-30 16:22:16.673 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-30 16:22:16.675 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-30 16:22:16.676 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-30 16:22:16.677 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-30 16:22:16.678 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-30 16:22:16.680 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-30 16:22:16.682 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-30 16:22:16.683 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n"
     ]
    }
   ],
   "source": [
    "# app.py\n",
    "import streamlit as st\n",
    "import numpy as np\n",
    "import joblib\n",
    "import os\n",
    "import io\n",
    "\n",
    "st.set_page_config(page_title=\"Solar Power Prediction\", layout=\"centered\")\n",
    "st.title(\"Solar Power Generation Prediction\")\n",
    "\n",
    "st.write(\"Enter the input values and click Predict. If you don't have the model file in the app folder, upload it below.\")\n",
    "\n",
    "# --- Model loading: try local file first, otherwise allow upload ---\n",
    "MODEL_FILENAME = \"random_forest_model.joblib\"\n",
    "model = None\n",
    "\n",
    "# If model exists in repo folder, load it\n",
    "if os.path.exists(MODEL_FILENAME):\n",
    "    try:\n",
    "        model = joblib.load(MODEL_FILENAME)\n",
    "        st.success(f\"Loaded model from {MODEL_FILENAME}\")\n",
    "    except Exception as e:\n",
    "        st.warning(f\"Found {MODEL_FILENAME} but failed to load it: {e}\")\n",
    "\n",
    "# If not loaded, let user upload the model file\n",
    "if model is None:\n",
    "    uploaded_model = st.file_uploader(\"Upload trained model (.joblib)\", type=[\"joblib\"])\n",
    "    if uploaded_model is not None:\n",
    "        try:\n",
    "            # joblib.load accepts a file-like object\n",
    "            model = joblib.load(uploaded_model)\n",
    "            st.success(\"Model uploaded and loaded successfully.\")\n",
    "        except Exception as e:\n",
    "            st.error(f\"Failed to load uploaded model: {e}\")\n",
    "\n",
    "st.markdown(\"---\")\n",
    "\n",
    "# --- Input fields (temporary defaults based on your notebook) ---\n",
    "st.header(\"Input features (adjust if your model expects different features)\")\n",
    "\n",
    "temperature = st.number_input(\"Temperature (°C)\", min_value=-50.0, max_value=80.0, value=30.0, step=0.1)\n",
    "irradiance = st.number_input(\"Solar Irradiance (W/m²)\", min_value=0.0, max_value=2000.0, value=800.0, step=0.1)\n",
    "wind_speed = st.number_input(\"Wind Speed (m/s)\", min_value=0.0, max_value=100.0, value=3.0, step=0.1)\n",
    "humidity = st.number_input(\"Humidity (%)\", min_value=0.0, max_value=100.0, value=50.0, step=0.1)\n",
    "\n",
    "st.write(\"**IMPORTANT:** The order of features must match what the model was trained on. If your model was trained on different features or a different order, update the input order below or rebuild the model accordingly.\")\n",
    "\n",
    "# If your model expects a different order, edit `input_data` to match that order.\n",
    "input_data = np.array([[temperature, irradiance, wind_speed, humidity]])\n",
    "\n",
    "# Show input preview\n",
    "st.subheader(\"Input preview\")\n",
    "st.write(pd := {\n",
    "    \"Temperature\": temperature,\n",
    "    \"Irradiance\": irradiance,\n",
    "    \"Wind Speed\": wind_speed,\n",
    "    \"Humidity\": humidity\n",
    "})\n",
    "st.write(input_data)\n",
    "\n",
    "# --- Predict button ---\n",
    "if st.button(\"Predict\"):\n",
    "    if model is None:\n",
    "        st.error(\"No model available. Upload a trained .joblib model or place it in the app folder with name: \" + MODEL_FILENAME)\n",
    "    else:\n",
    "        try:\n",
    "            pred = model.predict(input_data)\n",
    "            # handle array-like predictions\n",
    "            if hasattr(pred, \"__len__\"):\n",
    "                out = float(pred[0])\n",
    "            else:\n",
    "                out = float(pred)\n",
    "            st.success(f\"Estimated Solar Power Output: **{out:.2f} kW**\")\n",
    "        except Exception as e:\n",
    "            st.error(f\"Prediction failed: {e}\")\n",
    "\n",
    "st.markdown(\"---\")\n",
    "st.write(\"If prediction fails with a shape / feature error, your model expects different features or preprocessing. Paste your model training feature list here and I will update the app for you.\")\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "04ef1bdf-c961-418a-a6f9-1f6e77e61c25",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.13.5"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
